[[rust_library]]
name = "ggen"
edition = "2018"
srcs = [
  "lib.rs",
  "basic.rs",
  "macros.rs",
]

[[rust_test]]
name = "ggen_test"
edition = "2018"
srcs = [
  "lib.rs",
  "basic.rs",
  "macros.rs",
]
