[[rust_library]]
name = "cbs_plugin_sdk"
edition = "2021"
srcs = ["lib.rs"]
cargo_deps = [
  { package = "flatbuffers", version = "=25.12.19" },
]

[[rust_test]]
name = "cbs_plugin_sdk_test"
edition = "2021"
srcs = ["lib.rs"]
cargo_deps = [
  { package = "flatbuffers", version = "=25.12.19" },
]
