[[rust_binary]]
name = "cbs"
edition = "2021"
root_source = "main.rs"
srcs = [
  "actions.rs",
  "bus.rs",
  "cargo.rs",
  "cargo_recipes.rs",
  "context.rs",
  "core.rs",
  "exec.rs",
  "main.rs",
  "plugin_abi.rs",
  "plugins.rs",
  "rust_plugin.rs",
  "workspace.rs",
]
deps = ["//util/cbs_plugin_sdk:cbs_plugin_sdk"]
cargo_deps = [
  { package = "libloading", version = "=0.8.9" },
  { package = "serde_json", version = "=1.0.117" },
  { package = "sha2", version = "=0.10.8" },
  { package = "toml", version = "=0.8.8" },
]
