[[rust_library]]
name = "ccl"
edition = "2018"
srcs = [
  "lib.rs",
  "ast.rs",
  "import_resolver.rs",
  "fmt.rs",
  "exec.rs",
  "eval.rs",
  "eval_tests.rs",
]
deps = ["//util/ggen:ggen"]

[[rust_binary]]
name = "cclfmt"
edition = "2018"
srcs = ["cclfmt.rs"]
deps = [
  ":ccl",
  "//util/flags:flags",
]

[[rust_binary]]
name = "cclc"
edition = "2018"
srcs = ["cclc.rs"]
deps = [
  ":ccl",
  "//util/flags:flags",
]

[[rust_test]]
name = "ccl_test"
edition = "2018"
root_source = "lib.rs"
srcs = [
  "lib.rs",
  "ast.rs",
  "import_resolver.rs",
  "fmt.rs",
  "exec.rs",
  "eval.rs",
  "eval_tests.rs",
]
deps = ["//util/ggen:ggen"]

